export const TESTS_LIST = [
  { id: 'hemogramme', name: 'NFS (Hémogramme complet)', unit: '', ref: '', category: 'Hématologie' },
  { id: 'vgm', name: 'VGM', unit: 'fL', ref: '80-100', category: 'Hématologie' },
  { id: 'ccmh', name: 'CCMH', unit: 'g/dL', ref: '32-36', category: 'Hématologie' },
  { id: 'ferritine', name: 'Ferritine', unit: 'µg/L', ref: '15-200', category: 'Hématologie' },
  { id: 'transferrine', name: 'Transferrine', unit: 'g/L', ref: '2.0-3.6', category: 'Hématologie' },
  { id: 'vitb12', name: 'Vitamine B12', unit: 'pg/mL', ref: '200-900', category: 'Hématologie' },
  { id: 'folates', name: 'Folates', unit: 'ng/mL', ref: '3.0-20.0', category: 'Hématologie' },
  { id: 'glycemie', name: 'Glycémie à jeun', unit: 'g/L', ref: '0.70-1.00', category: 'Biochimie' },
  { id: 'hba1c', name: 'HbA1c', unit: '%', ref: '<6.5', category: 'Biochimie' },
  { id: 'creatinine', name: 'Créatinine', unit: 'µmol/L', ref: '62-106', category: 'Biochimie' },
  { id: 'uree', name: 'Urée', unit: 'mmol/L', ref: '2.5-7.5', category: 'Biochimie' },
  { id: 'acide_urique', name: 'Acide urique', unit: 'µmol/L', ref: '140-360', category: 'Biochimie' },
  { id: 'ionogramme', name: 'Ionogramme (Na, K, Cl)', unit: 'mmol/L', ref: 'Varie', category: 'Biochimie' },
  { id: 'bilan_hepatique', name: 'Bilan hépatique complet', unit: 'UI/L', ref: '<40', category: 'Biochimie' },
  { id: 'asat', name: 'ASAT (TGO)', unit: 'UI/L', ref: '<35', category: 'Biochimie' },
  { id: 'alat', name: 'ALAT (TGP)', unit: 'UI/L', ref: '<35', category: 'Biochimie' },
  { id: 'ggt', name: 'GGT', unit: 'UI/L', ref: '<40', category: 'Biochimie' },
  { id: 'pal', name: 'PAL', unit: 'UI/L', ref: '40-130', category: 'Biochimie' },
  { id: 'bilirubine', name: 'Bilirubine totale', unit: 'µmol/L', ref: '<21', category: 'Biochimie' },
  { id: 'amylase', name: 'Amylase', unit: 'UI/L', ref: '28-100', category: 'Biochimie' },
  { id: 'lipase', name: 'Lipase', unit: 'UI/L', ref: '13-60', category: 'Biochimie' },
  { id: 'cholesterol', name: 'Cholesterol total', unit: 'g/L', ref: '<2.0', category: 'Lipides' },
  { id: 'hdl', name: 'HDL-Cholesterol', unit: 'g/L', ref: '>0.40', category: 'Lipides' },
  { id: 'ldl', name: 'LDL-Cholesterol', unit: 'g/L', ref: '<1.6', category: 'Lipides' },
  { id: 'triglycerides', name: 'Triglycérides', unit: 'g/L', ref: '<1.5', category: 'Lipides' },
  { id: 'tsh', name: 'TSH', unit: 'mUI/L', ref: '0.4-4.0', category: 'Hormones' },
  { id: 't3', name: 'T3 Libre', unit: 'pmol/L', ref: '3.5-6.5', category: 'Hormones' },
  { id: 't4', name: 'T4 Libre', unit: 'pmol/L', ref: '11-23', category: 'Hormones' },
  { id: 'lh', name: 'LH', unit: 'UI/L', ref: 'Varie', category: 'Hormones' },
  { id: 'fsh', name: 'FSH', unit: 'UI/L', ref: 'Varie', category: 'Hormones' },
  { id: 'prolactine', name: 'Prolactine', unit: 'µg/L', ref: '<20', category: 'Hormones' },
  { id: 'testosterone', name: 'Testostérone', unit: 'nmol/L', ref: '8.0-30.0', category: 'Hormones' },
  { id: 'estradiol', name: 'Estradiol', unit: 'pmol/L', ref: 'Varie', category: 'Hormones' },
  { id: 'cortisol', name: 'Cortisol', unit: 'nmol/L', ref: '140-700', category: 'Hormones' },
  { id: 'psa', name: 'PSA', unit: 'µg/L', ref: '<4.0', category: 'Hormones' },
  { id: 'troponine', name: 'Troponine I', unit: 'µg/L', ref: '<0.04', category: 'Cardiaque' },
  { id: 'ck_mb', name: 'CK-MB', unit: 'UI/L', ref: '<25', category: 'Cardiaque' },
  { id: 'd_dimeres', name: 'D-Dimères', unit: 'µg/mL', ref: '<0.50', category: 'Cardiaque' },
  { id: 'bnp', name: 'BNP', unit: 'pg/mL', ref: '<100', category: 'Cardiaque' },
  { id: 'crp', name: 'CRP', unit: 'mg/L', ref: '<5', category: 'Inflammation' },
  { id: 'vsh', name: 'VSH', unit: 'mm/h', ref: '<20', category: 'Inflammation' },
  { id: 'tp', name: 'TP (Quick)', unit: '%', ref: '70-100', category: 'Coagulation' },
  { id: 'tca', name: 'TCA', unit: 's', ref: '25-35', category: 'Coagulation' },
  { id: 'inr', name: 'INR', unit: '', ref: '0.9-1.2', category: 'Coagulation' },
  { id: 'fibrinogene', name: 'Fibrinogène', unit: 'g/L', ref: '2.0-4.0', category: 'Coagulation' },
  { id: 'vitamine_d', name: 'Vitamine D (25-OH)', unit: 'ng/mL', ref: '30-60', category: 'Vitamines' },
  { id: 'fer', name: 'Fer sérique', unit: 'µmol/L', ref: '11-30', category: 'Minéraux' },
  { id: 'magnesium', name: 'Magnésium', unit: 'mmol/L', ref: '0.75-1.05', category: 'Minéraux' },
  { id: 'zinc', name: 'Zinc', unit: 'µmol/L', ref: '11-22', category: 'Minéraux' },
  { id: 'calcium', name: 'Calcium', unit: 'mmol/L', ref: '2.15-2.55', category: 'Minéraux' },
  { id: 'phosphore', name: 'Phosphore', unit: 'mmol/L', ref: '0.80-1.45', category: 'Minéraux' },
  { id: 'groupage', name: 'Groupage sanguin + RAI', unit: '', ref: 'A/B/AB/O', category: 'Sérologie' },
  { id: 'coombs', name: 'Coombs direct', unit: '', ref: 'Négatif', category: 'Sérologie' },
  { id: 'hiv', name: 'Sérologie VIH', unit: '', ref: 'Négatif', category: 'Sérologie' },
  { id: 'vhb', name: 'Sérologie VHB', unit: '', ref: 'Négatif', category: 'Sérologie' },
  { id: 'vhc', name: 'Sérologie VHC', unit: '', ref: 'Négatif', category: 'Sérologie' },
  { id: 'toxo', name: 'Toxoplasmose', unit: '', ref: 'Négatif', category: 'Sérologie' },
  { id: 'rubéole', name: 'Rubéole', unit: '', ref: 'Négatif', category: 'Sérologie' },
  { id: 'urine', name: 'ECBU (Urine)', unit: '', ref: 'Négatif', category: 'Microbiologie' },
  { id: 'hemoculture', name: 'Hémoculture', unit: '', ref: 'Négatif', category: 'Microbiologie' },
];

export const STATUS_CONFIG = {
  demanded:   { label: 'Demande',            color: 'bg-amber-100 text-amber-800 border-amber-200',  icon: 'fa-file-medical', next: 'collected',    action: 'Prélever' },
  collected:  { label: 'Échantillon collecté', color: 'bg-sky-100 text-sky-800 border-sky-200',      icon: 'fa-vial',         next: 'picked_up',    action: 'Prendre en charge' },
  picked_up:  { label: 'Pris en charge',     color: 'bg-purple-100 text-purple-800 border-purple-200', icon: 'fa-truck',        next: 'delivered',    action: 'Livrer au labo' },
  delivered:  { label: 'Livré',              color: 'bg-indigo-100 text-indigo-800 border-indigo-200', icon: 'fa-box-open',     next: 'processing',   action: 'Commencer analyse' },
  processing: { label: 'En cours',           color: 'bg-orange-100 text-orange-800 border-orange-200', icon: 'fa-microscope',   next: 'completed',    action: 'Finaliser' },
  completed:  { label: 'Terminé',            color: 'bg-emerald-100 text-emerald-800 border-emerald-200', icon: 'fa-check-circle', next: null,           action: null }
};

export const ROLE_NAMES = {
  doctor: 'Médecin',
  nurse: 'Infirmier(e)',
  agent: 'Agent de livraison',
  lab: 'Personnel de laboratoire',
  admin: 'Administrateur'
};

export const SEED_USERS = [
  { id: 1, email: 'doctor@labconnect.fr', password: 'doctor', role: 'doctor', name: 'Dr. Youssef El Azouzi', clinic: 'Cabinet Médical Central' },
  { id: 2, email: 'nurse@labconnect.fr', password: 'nurse', role: 'nurse', name: 'Inf. Hannan Boussaha', clinic: 'Cabinet Médical Central' },
  { id: 3, email: 'agent@labconnect.fr', password: 'agent', role: 'agent', name: 'Hamza Karmi', company: 'LabLogistics' },
  { id: 4, email: 'lab@labconnect.fr', password: 'lab', role: 'lab', name: 'Tech. Mariam Randi', lab: 'Laboratoire BioAnalyse' },
  { id: 99, email: 'admin@labconnect.fr', password: 'admin1234', role: 'admin', name: 'Administrateur' }
];
